version: '3.8'

services:
  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "11180:80"
    volumes:
      - type: bind
        source: C:\Users\rhys\Desktop\example-html
        target: /usr/share/nginx/html
  nginx-backend:
    image: nginx:1.25.4-alpine
    ports:
      - "11181:80"