version: "3"
services:
  tomcat1:
    # docker run -p 28081:8080 localhost/tomcat-demo:9.0.75-jdk17
    image: localhost/tomcat-demo:9.0.75-jdk17
    ports:
      - "28081:8080"
  tomcat2:
    image: localhost/tomcat-demo:9.0.75-jdk17
    ports:
      - "28082:8080"
  tool:
    image: busybox:1.28
    command:
      - sleep
      - "3600"
